In [1]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


In [3]:
#1 of slicing strings
print(element[:4])
print(element[4:])
print(element[:])

oxyg
en
oxygen


In [4]:
#2 of slicing strings
print(element[-1])
print(element[-2])

n
e


In [5]:
#3 of splicing string
#it starts at the second character and stops 1 before the end
print(element[1:-1])

xyge


In [7]:
#4 of splicing strings
#They both are empty since 3:3  is a string that contains no letters, even putting the : will do nothing since the string will be going from 0 to 0.
import numpy 
mdata = numpy.loadtxt("inflammation-01.csv",delimiter = ",")
print(mdata[3:3, 4:4])
print(mdata[3:3, :])

[]
[]


In [8]:
#1 Stacking arrays 
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
#Additional code that slices the first and last columns of A, and stacks them into a 3x2 array. 
print(numpy.hstack([numpy.vstack(A[:,0]),numpy.vstack(A[:,2])]))

[[1 3]
 [4 6]
 [7 9]]


In [24]:
numpy.diff(numpy.array([ 0,  2,  5,  9, 14])
) 

array([2, 3, 4, 5])

In [ ]:
#1 Change in inflammation 
#We would want to look at at axis = 1, as it would allow us to compare inflammation differences for each patient over time.

In [ ]:
#2 Change in inflammation
#Asuuming this is a pateint data file. The shape after running the diff() function will result in the array being (60,39) as 60 represents the rows (which is each patient) and the original 40 represented the differences in inflammation for each patient and the diff function allows us to find out the change amongst each patients' inflammation (in this case) and by doing so we end up losing a column.

In [26]:
#3 Change in inflammation
#It does matter if there is an increase or decrease in inflammation if we are trying to find the largest change. A way to get the largest chnage would be to take the absolute value of all of the inflammation numbers prior to figuring the difference amongst the inflammation numbers. This way it would only display the change in inflammation by only taking the magnitude into account. 
print(numpy.max(numpy.abs(numpy.diff(mdata)), axis = 1))

[12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.
 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.
 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11. 12. 14. 11.]
